### ISSUE TITLE
build better prepublish flow

### ISSUE THREAD

**Issue by mmeester** [MatiseAms/henris#11]

**Comment by silvandiepen** [comment]
prepublishOnly now 
- test:
	- Creates settings from json.
	- Runs test on default css output.
	- Runs test on full css output.
	- Runs test on empty css output.
	- Runs test on output function.
	- Runs test on actual checking if empty really has no output.
- Build:
	- Creates settings from json.
	- Removes dist css files.
	- Creates new dist css files. 
	
And won't publish when anything is wrong.
