### ISSUE TITLE
Add debug mode

### ISSUE THREAD

**Issue by mmeester** [MatiseAms/henris#17]
For example, put debug mode on on develop and off on production so we will never see red borders on images without an alt=""

**Comment by silvandiepen** [comment]
Good idea. 

We could easily accomplish this by adding an output variable. $output-debug which can be set false on production and default true on development. 

The only thing is how to add this in the project. The project will need to make the switch in which file to use or variable to set. Any ideas? 

Using the following in the assets/scss/app.scss (in case of nuxt project) in the top could do. But $dev-mode has to come from somewhere, or just the output-debug: true need to come from somewhere. (or false). 

```scss
@if $dev-mode{
	$output-debug: true; 
}
```

**Comment by silvandiepen** [comment]
Debug mode is implemented, but should be enforced from the project.

By default the app.scss will look like this:

```
@import '~henris';
```
There should be a separate app.scss or variable set when the production mode is on and should include an app.scss looking like this:

```

```
@import '~henris/custom-output';
$output: set-output('debug',false);
@import '~henris';
```
