### ISSUE TITLE
css-antialias doesn't work

### ISSUE THREAD

**Issue by DennisMatise** [MatiseAms/henris#32]
For some reason this doesn't get included but when you overwrite it, it does

**Comment by silvandiepen** [comment]
Probably because its off by default, the reset. Either have to change the default or anything else. 

Can you check why and make a PR?

**Comment by silvandiepen** [comment]
@DennisMatise

**Comment by silvandiepen** [comment]
@DennisMatise

**Comment by silvandiepen** [comment]
Fixed.. I think
